package LSHFIndex;

import global.Vector100Dtype;
import heap.Heapfile;

import java.util.Map;
import java.util.Random;

/**
 * A layer is a collection of " n = num_hash_functions" unique hash functions
 * (h_1...h_n)
 * h1,h2,h3 ... form a layer together.
 * a hash is generated by a layer after
 * evaluating an input on all the hash functions in the layer.
 * num_hash_functions - hashes per layer
 * hashFunctions - array of hashfunctions
 * layer_map - a map that maps generated hash to its corresponding heapfile
 *
 */

// Layer hash is an array of integers.
// this array will be converted to strings when necessary for storing heapfile
// name
// We want to keep the hash as an array of integers instead of
// one integer or one string to avoid the following situation:
// Suppose we have 2 hash functions h1 and h2
// for 2 different inputs i1 and i2, suppose we get
// h1(i1) = 32 h2(i1) = 3
// h1(i2) = 3 h2(i2) = 23
// if we use single string/int which is a concatenation of h1 and h2,
// both the inputs will end up having the same hash 323. We do not want this.

public class Layer {
    private Vector100Dtype[] projVectors;
    private Random random;
    private int noOfHashFunctions;
    private int binLength;


    public Layer(int k, int w){
        this.noOfHashFunctions = k;
        this.binLength = w;
        this.random = new Random();
        this.projVectors = setProjection100DVectors();
    }

    public Vector100Dtype[] setProjection100DVectors() {
        projVectors = new Vector100Dtype[noOfHashFunctions];
        int max = 10000;
        int min = -10000;
        for(int k = 0; k < noOfHashFunctions; k++){
            projVectors[k] = new Vector100Dtype();
            for (int i = 0; i < 100; i++) {
                short randomNumber = (short) (random.nextInt(max - min + 1) + min);
                projVectors[k].vector[i] = randomNumber;
            }
        }
        return projVectors;
    }

    public int[] GetLayerHash(Vector100Dtype input) {
        int dotProduct = 0;
        int[] hash = new int[noOfHashFunctions];
        for(int k = 0; k < noOfHashFunctions; k++){
            for (int i = 0; i < 100; i++) {
                dotProduct += projVectors[k].vector[i] * input.vector[i];
            }
            hash[k] = Math.floorDiv(dotProduct, binLength);
        }
        
        return hash;
    }

    public String GetLayerHashAsString(Vector100Dtype input) {
        int[] hash = GetLayerHash(input);
        StringBuilder hashString = new StringBuilder();
        for (int value : hash) {
            hashString.append(value).append("_");
        }
        // Remove the trailing underscore
        if (hashString.length() > 0) {
            hashString.setLength(hashString.length() - 1);
        }
        return hashString.toString();
    }
}
